export const publicRoutes = Object.freeze({
    MAIN:{
        name:"mainPage",
        route:'/'
    },
    JOBS:{
        name:"jobsPage",
        route:'/jobs'
    },
    ESTATE:{
        name:"realEstate",
        route:'/realEstate'
    },
    SERVICES:{
        name:"services",
        route:'/services'
    },
    TRUCKS:{
        name:"trucks",
        route:'/trucks'
    },
    FORM:{
        name:"adsForm",
        route:'/form'
    }
})